name: CD HEROKU

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_APP_TOKEN}}
          heroku_app_name: "seeds-articles"
          heroku_email: "mgg7934@hotmail.com"
          remote_branch: "main"

      